export { default } from "./src/wdk-core/wdk-manager-v3.js";
export { default as HRPC } from "./spec/hrpc/index.js";
export { default as bundle } from "./bundle/worklet.bundle.mjs";
export type FeeRates = any;
export type TransferOptions = any;
export type TransferResult = any;
export type IWalletAccount = any;
export type Seed = import("./src/wdk-core/wdk-manager.js").Seed;
export type Seeds = import("./src/wdk-core/wdk-manager.js").Seeds;
export type WdkConfig = import("./src/wdk-core/wdk-manager.js").WdkConfig;
export type TransferConfig = import("./src/wdk-core/wdk-manager.js").TransferConfig;
