# .github/workflows/local-publish-test.yml
name: local-publish-test
on:
  workflow_dispatch:
    inputs:
      dry_run:
        type: boolean
        default: true
        required: false
jobs:
  call:
    uses: ./.github/workflows/publish.yml
    with:
      dry_run: ${{ inputs.dry_run }}
    secrets: inherit
